### ISSUE TITLE
user-can-search-for-a-pokemon

### ISSUE THREAD

**Issue by Jc-Leon** [Jc-Leon/PokeStats#2]
## 🖼️ Wireframes

<img width="597" alt="Screen Shot 2021-07-27 at 1 31 36 PM" src="https://user-images.githubusercontent.com/84432043/127223325-abfce0c8-af82-44ac-80b8-5c943242c984.png">
<img width="601" alt="Screen Shot 2021-07-27 at 1 32 04 PM" src="https://user-images.githubusercontent.com/84432043/127223360-9a4a2948-762d-4f95-b4f6-18972764389d.png">

## ✅ Task List

- [x] Add background gif
- [x] Center pokestats image on gif
- [x] Center input text box with placeholder "who will you choose?"
- [x] Set detective pikachu as submit icon
- [x] On add event listener on pikachu click to display new page of pokemon stats
- [x] All main page items to be top place on top of page
- [x] Place calmer gif as new page background
- [x] Make a column with div containers to separate image name stats fav and exit icon
- [x] image and name containter to be updated
- [x] Make table to display stats to be updated with values
- [x] Clean up any unused CSS
- [x] Ensure page is desktop and mobile responsive
- [x] Fix any errors
