### ISSUE TITLE
user-can-add-a-pokemon-to-a-comparison-list

### ISSUE THREAD

**Issue by Jc-Leon** [Jc-Leon/PokeStats#4]
![Screen Shot 2021-07-30 at 11 08 34 AM](https://user-images.githubusercontent.com/84432043/127694427-befd476a-a2b6-4e9e-92fc-ad10098411f6.png)

## ✅ Task List

- [x] When pokemon name is searched input field will be revert to its original placeholder text
- [x] On search pokemon should generate next to first entry on main page search
- [x] Make sure page is mobile responsive
