### ISSUE TITLE
user-can-delete-a-pokemon-from-comparison-list

### ISSUE THREAD

**Issue by Jc-Leon** [Jc-Leon/PokeStats#7]
## 🖼️ Wireframes

<img width="550" alt="Screen Shot 2021-08-04 at 1 12 55 PM" src="https://user-images.githubusercontent.com/84432043/128248379-4b3e6b09-a35f-4fdf-9e89-4d649b0fe35c.png">

## ✅ Task List

- [x] User is able to able to add an entry on homepage
- [x] User is able to add another entry on secondary page
- [x] User is able to delete entries on click using top right X
- [x] Erase unused CSS
-
