### ISSUE TITLE
user-can-favorite-a-pokemon

### ISSUE THREAD

**Issue by Jc-Leon** [Jc-Leon/PokeStats#9]
## 🖼️ Wireframes
<img width="638" alt="Screen Shot 2021-08-05 at 5 28 00 PM" src="https://user-images.githubusercontent.com/84432043/128437907-64e6aff6-a510-433b-8d70-9185c26f9bc6.png">

## ✅ Task List

- [ ] User is able to favorite their pokmons they searched for 
- [ ] User able to toggle favorite pokemon to either favorite or unfavorite
- [ ] Favorited pokemons are sent to local storage and stored for a later usage
- [ ] Place floating pokeball gif on top left to indicate favorite pokemon tab
- [ ] Clean any unused CSS
- [ ] Make sure application is mobile responsive
